{{- if and .Values.mlrun.enabled (not .Values.global.infrastructure.aws.s3NonAnonymous) -}}
{{- if not .Values.minio.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.credentialsSecretName | default "minio-credentials" }}
  labels:
    {{- include "mlrun-ce.common.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.rootUser | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.rootPassword | b64enc | quote }}
{{- end -}}
{{- end -}}
