{{- if .Values.pipelines.enabled -}}
{{- if not .Values.pipelines.minio.existingSecret -}}
apiVersion: v1
data:
  accesskey: {{ .Values.pipelines.minio.accessKey | b64enc | quote }}
  secretkey: {{ .Values.pipelines.minio.secretKey | b64enc | quote }}
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: {{ .Values.pipelines.minio.existingSecretName | default "mlpipeline-minio-artifact" }}
type: Opaque
{{- end -}}
{{- end -}}
