apiVersion: v1
description: MLRun Open Source Stack
home: https://iguazio.com
icon: https://www.iguazio.com/wp-content/uploads/2019/10/Iguazio-Logo.png
maintainers:
- email: mlrun@iguazio.com
  name: MLRun
  url: https://www.mlrun.org/
name: mlrun-ce
version: 0.10.0
